// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7kVSpt7jtqBwJN0RwhNQ7fjx0YK7IXlg',
    appId: '1:1080862649227:web:6b2e23a9b7abb5a1b89d8e',
    messagingSenderId: '1080862649227',
    projectId: 'washeasy-7d800',
    authDomain: 'washeasy-7d800.firebaseapp.com',
    storageBucket: 'washeasy-7d800.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUaZ6AkA4TX2UfHTQU4ie83nddOVPB7A0',
    appId: '1:1080862649227:android:28896aa8dabee35cb89d8e',
    messagingSenderId: '1080862649227',
    projectId: 'washeasy-7d800',
    storageBucket: 'washeasy-7d800.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP8JCbWAgmH7ShBApe8YFrBF7PucOgFFI',
    appId: '1:1080862649227:ios:25982946388e8c9bb89d8e',
    messagingSenderId: '1080862649227',
    projectId: 'washeasy-7d800',
    storageBucket: 'washeasy-7d800.firebasestorage.app',
    iosBundleId: 'com.example.washeasy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP8JCbWAgmH7ShBApe8YFrBF7PucOgFFI',
    appId: '1:1080862649227:ios:25982946388e8c9bb89d8e',
    messagingSenderId: '1080862649227',
    projectId: 'washeasy-7d800',
    storageBucket: 'washeasy-7d800.firebasestorage.app',
    iosBundleId: 'com.example.washeasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7kVSpt7jtqBwJN0RwhNQ7fjx0YK7IXlg',
    appId: '1:1080862649227:web:9c6a498c5f478cebb89d8e',
    messagingSenderId: '1080862649227',
    projectId: 'washeasy-7d800',
    authDomain: 'washeasy-7d800.firebaseapp.com',
    storageBucket: 'washeasy-7d800.firebasestorage.app',
  );
}
